name: Clang Tidy/Format

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install base dependencies
      run: |
        sudo apt update
        sudo apt install cmake make pkg-config libx11-dev xcb libx11-xcb-dev libxkbcommon-dev libgtk-3-dev sassc
    
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 5.15.2
        
    - name: Compile App with CMake
      run: |
        mkdir build
        cd build
        cmake ../timesweeper -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=/usr -DUSE_QT6=OFF
        
#     - name: Clang-Tidy
#       run: |
#         cd build
#         run-clang-tidy -checks='modernize-*' > clang-tidy-log.txt
#        clang-tidy -checks='readability-identifier-naming' ../.clang-tidy > clang-tidy-log.txt

    - name: Clang-Tidy
      uses: HorstBaerbel/action-clang-tidy@1.2
      with:
        scandir: 'timesweeper'
        builddir: 'build'
        extensions: 'h,cpp'
        
    - name: Clang-Format
      run: |
        cd build
        clang-format --style=file ../.clang-format > clang-format-log.txt
        
    - name: Publish Result Files
      uses: actions/upload-artifact@v3
      with:
        name: timesweeper-analysis
        path: build/clang-format-log.txt
#          build/clang-tidy-log.txt
