name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install base dependencies
      run: |
        sudo apt update
        sudo apt install cmake make pkg-config libx11-dev xcb libx11-xcb-dev libxkbcommon-dev libgtk-3-dev sassc
    
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 5.15.2
        
    - name: Build App with CMake
      run: |
        mkdir build
        cd build
        cmake ../timesweeper -g "Unix Makefiles" -DCMAKE_PREFIX_PATH="/usr/lib64/cmake"
        make
